MODEL:
  NUM_CLASSES: 21
  SELF_SUPERVISED: True
  SELF_SUPERVISOR:
    TYPE: "rotation"
    DROPOUT: 0.5
    SELF_ADE_BREAKPOINTS: (21,25,30,35,40)
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TEST: ("comic_test",)
SOLVER:
  BATCH_SIZE: 32
OUTPUT_DIR: 'output_comic_self_ade'
